apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/www/html  # Adjust this path as per your environment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Pod 1 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod1
    
spec:
  containers:
  - name: pod1-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

---
# Pod 2 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  
  
spec:
  containers:
  - name: pod2-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app  # Label selector to match pods
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pods
  type: ClusterIP  # Expose internally only
