# PersistentVolume definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data  # Adjust this path as per your environment

---
# PersistentVolumeClaim definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Pod 1 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1-container
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

---
# Pod 2 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: pod2-container
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc
