# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-volume
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    image: httpd-
    ports:
      - containerPort: 80 

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: container2
    image: httpd
    ports:
      - containerPort: 80 


