# PersistentVolume definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/www/html



 

---
# PersistentVolumeClaim definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Pod 1 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod1
    labels:
    app: my-app
spec:
  containers:
  - name: pod1-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

---
# Pod 2 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod2
    labels:
    app: my-app1
spec:
  containers:
  - name: pod2-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app 
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pods
  type: ClusterIP  # Expose internally only
