apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data  # Adjust this path as per your environment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
# Pod 1 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod1
    labels:
    app: my-pod1
spec:
  containers:
  - name: pod1-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

---
# Pod 2 definition
apiVersion: v1
kind: Pod
metadata:
  name: pod2
    labels:
    app: my-pod2
spec:
  containers:
  - name: pod2-container
    image: httpd
    volumeMounts:
    - name: html-volume
      mountPath: /var/www/html
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: my-pvc

