apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: httpd-namespace
spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: httpd-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-datacenter
  template:
    metadata:
      labels:
        app: node-app-datacenter
    spec:
      containers:
        - name: node-container-datacenter
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 80
