---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
  labels:
    app: my-app
spec:
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: task-pv-container
      image: httpd
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/"
          name: my-pvc
...